[package]
name = "proust"
version = "0.0.5"
authors = ["Madison McGaffin <greyhill@gmail.com>"]
build = "build.rs"

[lib]
name = 'proust'
crate-type = ["rlib", "dylib"]

[dependencies.libc]
version = "*"
